# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redash < Formula
  desc "Command-line client for the Redash REST API (agent-first)"
  homepage "https://github.com/leroy/redash"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leroy/redash/releases/download/v1.0.1/redash_1.0.1_darwin_x86_64.tar.gz"
      sha256 "47d5ffac6898f866ac2216f4d9015cd36ee69d93565726af614e9448274932da"

      define_method(:install) do
        bin.install "redash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leroy/redash/releases/download/v1.0.1/redash_1.0.1_darwin_arm64.tar.gz"
      sha256 "127e7ad7dc8c3d7886de8ce876ddc7489a4515f1b8e4f2c497626d2e3bef0783"

      define_method(:install) do
        bin.install "redash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leroy/redash/releases/download/v1.0.1/redash_1.0.1_linux_x86_64.tar.gz"
      sha256 "d4ee81ac44a1813a4dd7e3bf5421f3e73248decda0aaabb985607ac80cefc20f"
      define_method(:install) do
        bin.install "redash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leroy/redash/releases/download/v1.0.1/redash_1.0.1_linux_arm64.tar.gz"
      sha256 "51942690c0202143ee3bd620319632653ec8ab379bdcc32c74c39b0a6a3f19a8"
      define_method(:install) do
        bin.install "redash"
      end
    end
  end

  test do
    assert_match "redash #{version}", shell_output("#{bin}/redash version")
    assert_match "Overview", shell_output("#{bin}/redash manual --list-topics")
  end
end
