# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Redash < Formula
  desc "Command-line client for the Redash REST API (agent-first)"
  homepage "https://github.com/leroy/redash"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/leroy/redash/releases/download/v1.1.0/redash_1.1.0_darwin_x86_64.tar.gz"
      sha256 "5538d879e20e75c19c05a5b85fee6f8c57b58890016b4a1a54debc2f862a4ed1"

      define_method(:install) do
        bin.install "redash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/leroy/redash/releases/download/v1.1.0/redash_1.1.0_darwin_arm64.tar.gz"
      sha256 "99b5ae4c6240cc2f6eb850e8963e37a91267a519f4e885d5dadfd5e3e629d77b"

      define_method(:install) do
        bin.install "redash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/leroy/redash/releases/download/v1.1.0/redash_1.1.0_linux_x86_64.tar.gz"
      sha256 "547b2e8eac171e877a8f51711913435e68d2fd212e63fb3df07ca7239d09fe7d"
      define_method(:install) do
        bin.install "redash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/leroy/redash/releases/download/v1.1.0/redash_1.1.0_linux_arm64.tar.gz"
      sha256 "e418e7deb1141e0239d599805968f8c5b1fe9434c20585db1b05218324e6fd35"
      define_method(:install) do
        bin.install "redash"
      end
    end
  end

  test do
    assert_match "redash #{version}", shell_output("#{bin}/redash version")
    assert_match "Overview", shell_output("#{bin}/redash manual --list-topics")
  end
end
